name: Full QR Generator

on:
  workflow_dispatch:

jobs:
  build-qr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate QR image from Secret
        run: |
          # ساخت QR با سرویس توکن دار
          curl -o qr.png "https://api.example-qr-service.com/create?token=${{ secrets.QR }}&size=200x200"

      - name: Generate index.html
        run: |
          echo "<!DOCTYPE html>
          <html lang='fa'>
          <head>
            <meta charset='UTF-8'>
            <title>QR Code Full</title>
          </head>
          <body>
            <h1>QR ساخته شده از Secret</h1>
            <img src='qr.png' alt='QR Code' />
            <p>Secret از Actions در سرویس QR استفاده شده است.</p>
          </body>
          </html>" > index.html

      - name: Upload all as artifact
        uses: actions/upload-artifact@v3
        with:
          name: qr-full
          path: |
            index.html
            qr.png
